replicaCount: 1

image:
  repository: ghcr.io/sraisl/faker-api
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8888

resources: {}

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
